<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ScreenLight</AssemblyName>
    <RootNamespace>ScreenLight</RootNamespace>
    <Version>1.1.0</Version>
    <ApplicationIcon>Assets\ScreenLight.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RestoreSources></RestoreSources>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\ScreenLight.ico" LogicalName="ScreenLight.AppIcon" />
  </ItemGroup>
</Project>
